**Lasso Regression:** To overcome the overfitting of the model Lasso Regression is used. L1 Regularization is used in Lasso Regression.

1. Lasso helps to reduce number of features when weights are exactly equal to zero.
2. Lasso rgression estimates the sparse cofficients.

**L1 Regularization:**
In L1 regularization L1 penality is added to cost function. mean squred error sum of the absolute cofficient is added and multiplied with alpha to reduce the cost function.

             Cost function = mse(ypred,yactual) + alpha *(sum(|slope|)

In [525]:
#importing required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

The data set we have to find the strength of the concerte (csMPa-target variable)

input variables-['cement', 'slag', 'flyash', 'water', 'superplasticizer'
'coarseaggregate', 'fineaggregate', 'age']

In [526]:
lasso_dataset=pd.read_csv("/content/Concrete_Data_Yeh.csv")
# reading the data frame using pandas

In [527]:
lasso_dataset.head()

   cement   slag  flyash  water  ...  coarseaggregate  fineaggregate  age  csMPa
0   540.0    0.0     0.0  162.0  ...           1040.0          676.0   28  79.99
1   540.0    0.0     0.0  162.0  ...           1055.0          676.0   28  61.89
2   332.5  142.5     0.0  228.0  ...            932.0          594.0  270  40.27
3   332.5  142.5     0.0  228.0  ...            932.0          594.0  365  41.05
4   198.6  132.4     0.0  192.0  ...            978.4          825.5  360  44.30

[5 rows x 9 columns]

In [528]:
lasso_dataset.shape

(1030, 9)

In [529]:
lasso_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cement            1030 non-null   float64
 1   slag              1030 non-null   float64
 2   flyash            1030 non-null   float64
 3   water             1030 non-null   float64
 4   superplasticizer  1030 non-null   float64
 5   coarseaggregate   1030 non-null   float64
 6   fineaggregate     1030 non-null   float64
 7   age               1030 non-null   int64
 8   csMPa             1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.5 KB

In [530]:
lasso_dataset.corr()

                    cement      slag  ...       age     csMPa
cement            1.000000 -0.275216  ...  0.081946  0.497832
slag             -0.275216  1.000000  ... -0.044246  0.134829
flyash           -0.397467 -0.323580  ... -0.154371 -0.105755
water            -0.081587  0.107252  ...  0.277618 -0.289633
superplasticizer  0.092386  0.043270  ... -0.192700  0.366079
coarseaggregate  -0.109349 -0.283999  ... -0.003016 -0.164935
fineaggregate    -0.222718 -0.281603  ... -0.156095 -0.167241
age               0.081946 -0.044246  ...  1.000000  0.328873
csMPa             0.497832  0.134829  ...  0.328873  1.000000

[9 rows x 9 columns]

In [531]:
lasso_features=lasso_dataset.drop(['superplasticizer','csMPa'],axis=1)
lasso_target=lasso_dataset['csMPa']
# splitting the dataset into train and test

**Standardization:**
Its is used when the data is inthe form of Guassian or normal distribution. But not necessarily to be in normal distribution. It is used when we want zero mean and standard deviation is unit. Mean and standard devation is used to scale the values. It is also called as z-score normalization.

*it standardizes by removing the mean or mean is centered and scaling to unit standard deviation. less sensitive to outliers.
   
                   standardization= x-mean/standard deviation

Implementing accuracy for training and testing data for different test sizes and alpha values

In [532]:
lasso_train_score=[]
lasso_test_score=[]
for i in range(1,5):
  size=i/10
  scaler= StandardScaler() # standarizing the model
  #lasso_features=scaler.fit_transform(lasso_features)
  X_train,X_test,y_train,y_test=train_test_split(lasso_features,lasso_target,test_size=size) #splitting the data set ro train and test
  lasso_model=Lasso(alpha=size) # Building the model with alpha values 0.1 to 05
  pipe=make_pipeline(scaler,lasso_model)
  pipe.fit(X_train,y_train) # tarning the model
  train_score=pipe.score(X_train,y_train)# Accuarcy of the training data
  test_score=pipe.score(X_test,y_test)# Accuracy of the testing data
  lasso_train_score.append(round((train_score*100),0))
  lasso_test_score.append(round((test_score*100),0))
print("Accuracy of training set:",lasso_train_score)
print("Accuracy of testing set: ",lasso_test_score)

#for test_size of 0.2 we can observe that training and testing score as same

Accuracy of training set: [61.0, 61.0, 61.0, 61.0]
Accuracy of testing set:  [61.0, 60.0, 58.0, 60.0]

In [533]:
lasso_train_score=[]
lasso_test_score=[]
for i in range(1,5):
  size=i/10
  scaler= StandardScaler() # standarizing the model
  #lasso_features=scaler.fit_transform(lasso_features)
  X_train,X_test,y_train,y_test=train_test_split(lasso_features,lasso_target,test_size=size) #splitting the data set ro train and test
  lasso_model=Lasso(alpha=size/10) # Building the model with alpha values 0.10 to 0.05
  pipe=make_pipeline(scaler,lasso_model)
  pipe.fit(X_train,y_train) # tarning the model
  train_score=pipe.score(X_train,y_train)# Accuarcy of the training data
  test_score=pipe.score(X_test,y_test)# Accuracy of the testing data
  lasso_train_score.append(round((train_score*100),0))
  lasso_test_score.append(round((test_score*100),0))
print("Accuracy of training set:",lasso_train_score)
print("Accuracy of testing set: ",lasso_test_score)

#for test_size of 0.3 we can observe that training and testing score as same

Accuracy of training set: [61.0, 62.0, 61.0, 62.0]
Accuracy of testing set:  [59.0, 57.0, 60.0, 60.0]

Implemeting accuarcy and MSE for different alpha values

In [541]:
lasso_score=[]
lasso_mse=[]
for i in range(1,11):
  lasso_alpha=i/10
  lasso_model=Lasso(alpha=lasso_alpha)
  lasso_model.fit(X_train,y_train)
  accuracy =lasso_model.score(X_test,y_test)
  lasso_score.append(round((accuracy*100),2))
  lasso_predict=lasso_model.predict(X_test)
  mse=mean_squared_error(lasso_predict,y_test)
  lasso_mse.append(round(mse,2))
print('\033[1m'+"Accuracy and MSE for different alpha values from 0.1 to 1"+'\033[0m')
print("Accuracy:",lasso_score)
print("MSE: ",lasso_mse)

Accuracy and MSE for different alpha values from 0.1 to 1
Accuracy: [59.88, 59.88, 59.88, 59.88, 59.88, 59.88, 59.88, 59.88, 59.89, 59.89]
MSE:  [105.95, 105.94, 105.94, 105.94, 105.93, 105.93, 105.93, 105.92, 105.92, 105.92]

In [542]:
lasso_score=[]
lasso_mse=[]
for i in range(1,11):
  lasso_alpha=i/100
  lasso_model=Lasso(alpha=lasso_alpha)
  lasso_model.fit(X_train,y_train)
  accuracy =lasso_model.score(X_test,y_test)
  lasso_score.append(round((accuracy*100),2))
  lasso_predict=lasso_model.predict(X_test)
  mse=mean_squared_error(lasso_predict,y_test)
  lasso_mse.append(round(mse,2))
print('\033[1m'+"Accuracy and MSE for different alpha values from 0.01 to 0.1"+'\033[0m')
print("Accuracy:",lasso_score)
print("MSE: ",lasso_mse)

Accuracy and MSE for different alpha values from 0.01 to 0.1
Accuracy: [59.87, 59.87, 59.87, 59.87, 59.87, 59.87, 59.87, 59.88, 59.88, 59.88]
MSE:  [105.95, 105.95, 105.95, 105.95, 105.95, 105.95, 105.95, 105.95, 105.95, 105.95]